import { Section } from 'src/app/models/form.interface';

export const NOTARIAL_FORM: Section[] = [
  {
    section: 'Notarial Commission',
    show: true,
    items: [
      {
        label: 'Last Name',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'lastName',
        show: true,
        default: '',
        path: 'lastName',
      },
      {
        label: 'First Name',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'firstName',
        show: true,
        default: '',
        path: 'firstName',
      },
      {
        label: 'Middle Name',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'middleName',
        show: true,
        default: '',
        path: 'middleName',
      },
      {
        label: 'Suffix',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'suffix',
        show: true,
        default: '',
        path: 'others.suffix',
        optional: true,
        placeholder: 'Suffix(optional)',
      },
      {
        label: 'Roll Number',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'roll_number',
        show: true,
        default: '',
        path: 'roll_number',
      },
      {
        label: 'IBP Chapter',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'ibp_chapter',
        show: true,
        default: '',
        path: 'ibo_chapter',
      },
      {
        label: 'Address Line 1',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
        fcname: 'address1',
        show: true,
        default: '',
        path: 'address1',
        placeholder: 'Street No./Building',
        optional: true,
      },
      {
        label: 'Address Line 2',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
        fcname: 'address2',
        show: true,
        default: '',
        path: 'address2',
        placeholder: 'Village/Apartment/Unit/Building/Etc.',
        optional: true,
      },
    ],
  },
];

export const PERIOD_OF_VALIDITY: Section[] = [
  {
    section: 'Period of Validity',
    show: true,
    items: [
      {
        label: 'Start Date',
        type: 'date',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'period_startDate',
        show: true,
        default: '',
        path: 'period_startDate',
      },
      {
        label: 'End Date',
        type: 'date',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'period_endDate',
        show: true,
        default: '',
        path: 'period_endDate',
      },
    ],
  },
];

export const ADDRESS_SELECT = [
  {
    label: 'Region',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'region',
    show: true,
    choices: [],
    choiceLabel: 'regDesc',
    choiceValue: 'regCode',
    default: '',
    path: 'region',
  },
  {
    label: 'Province',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'province',
    show: false,
    choices: [],
    choiceLabel: 'provDesc',
    choiceValue: 'provCode',
    default: '',
    path: 'province',
  },
  {
    label: 'City',
    type: 'select',
    required: false,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'cityMun',
    show: false,
    choices: [],
    choiceLabel: 'citymunDesc',
    choiceValue: 'citymunCode',
    default: '',
    path: 'cityMun',
  },
  {
    label: 'Barangay',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'barangay',
    show: false,
    default: '',
    choices: [],
    choiceLabel: 'brgyDesc',
    choiceValue: 'brgyCode',
    path: 'barangay',
  },
];
