import { AUTO_COMPLETE_FIELDS } from '../../../../../../../models/auto-complete.interface';
import { Section } from 'src/app/models/form.interface';

export const NOTARIAL_FORM: Section[] = [
  {
    section: 'Notarial Commission',
    show: true,
    items: [
      {
        label: 'Last Name',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'lastName',
        show: true,
        default: '',
        path: 'lastName',
        appearance: 'standard',
      },
      {
        label: 'First Name',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'firstName',
        show: true,
        default: '',
        path: 'firstName',
        appearance: 'standard',
      },
      {
        label: 'Middle Name',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'middleName',
        show: true,
        default: '',
        path: 'middleName',
        appearance: 'standard',
      },
      {
        label: 'Suffix',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'suffix',
        show: true,
        default: '',
        path: 'others.suffix',
        optional: true,
        placeholder: 'Suffix(optional)',
        appearance: 'standard',
      },
      {
        label: 'Email',
        type: 'email',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'email',
        show: true,
        default: '',
        path: 'email',
        appearance: 'standard',
      },
      {
        label: 'Mobile Number',
        type: 'mobileNumber',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'mobileNumber',
        show: true,
        default: '',
        path: 'mobileNumber',
        placeholder: '9123456789',
        appearance: 'standard',
      },
      {
        label: 'Roll Number',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'roll_number',
        show: true,
        default: '',
        path: 'roll_number',
        appearance: 'standard',
      },
    ],
  },
];

export const HOME_ADDRESS_FIELD: Section[] = [
  {
    section: 'Home Address Details',
    show: true,
    items: [
      {
        label: 'Address Line 1',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
        fcname: 'address1',
        show: true,
        default: '',
        path: 'address.address1',
        placeholder: 'Street No./Building',
        optional: true,
        appearance: 'standard',
      },
      {
        label: 'Address Line 2',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
        fcname: 'address2',
        show: true,
        default: '',
        path: 'address.address2',
        placeholder: 'Village/Apartment/Unit/Building/Etc.',
        optional: true,
        appearance: 'standard',
      },
    ],
  },
];
export const OFFICE_ADDRESS_FIELD: Section[] = [
  {
    section: 'Office Address Details',
    show: true,
    items: [
      {
        label: 'Address Line 1',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
        fcname: 'office_address1',
        show: true,
        default: '',
        path: 'office_address.address1',
        placeholder: 'Street No./Building',
        optional: true,
        appearance: 'standard',
      },
      {
        label: 'Address Line 2',
        type: 'text',
        colspan: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12 },
        fcname: 'office_address2',
        show: true,
        default: '',
        path: 'office_address.address2',
        placeholder: 'Village/Apartment/Unit/Building/Etc.',
        optional: true,
        appearance: 'standard',
      },
    ],
  },
];
export const PERIOD_OF_VALIDITY: Section[] = [
  {
    section: 'Period of Validity',
    show: true,
    items: [
      {
        label: 'Start Date',
        type: 'date',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'period_startDate',
        show: true,
        default: '',
        path: 'period_startDate',
        appearance: 'standard',
      },
      {
        label: 'End Date',
        type: 'date',
        colspan: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
        fcname: 'period_endDate',
        show: true,
        default: '',
        path: 'period_endDate',
        appearance: 'standard',
      },
    ],
  },
];

export const HOME_ADDRESS_SELECT = [
  {
    label: 'Region',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'region',
    show: true,
    choices: [],
    choiceLabel: 'regDesc',
    choiceValue: 'regCode',
    default: '',
    path: 'region',
  },
  {
    label: 'Province',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'province',
    show: true,
    choices: [],
    choiceLabel: 'provDesc',
    choiceValue: 'provCode',
    default: '',
    path: 'province',
  },
  {
    label: 'City',
    type: 'select',
    required: false,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'cityMun',
    show: true,
    choices: [],
    choiceLabel: 'citymunDesc',
    choiceValue: 'citymunCode',
    default: '',
    path: 'cityMun',
  },
  {
    label: 'Barangay',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'barangay',
    show: true,
    default: '',
    choices: [],
    choiceLabel: 'brgyDesc',
    choiceValue: 'brgyCode',
    path: 'barangay',
  },
];
export const OFFICE_ADDRESS_SELECT = [
  {
    label: 'Region',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'office_region',
    show: true,
    choices: [],
    choiceLabel: 'regDesc',
    choiceValue: 'regCode',
    default: '',
    path: 'office_region',
  },
  {
    label: 'Province',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'office_province',
    show: true,
    choices: [],
    choiceLabel: 'provDesc',
    choiceValue: 'provCode',
    default: '',
    path: 'office_province',
  },
  {
    label: 'City',
    type: 'select',
    required: false,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'office_cityMun',
    show: true,
    choices: [],
    choiceLabel: 'citymunDesc',
    choiceValue: 'citymunCode',
    default: '',
    path: 'office_cityMun',
  },
  {
    label: 'Barangay',
    type: 'select',
    required: true,
    colspan: { xs: 3, sm: 3, md: 3, lg: 3, xl: 3 },
    fcname: 'office_barangay',
    show: true,
    default: '',
    choices: [],
    choiceLabel: 'brgyDesc',
    choiceValue: 'brgyCode',
    path: 'office_barangay',
  },
];

export const IBP_CHAPTER_REGION_PROVINCE: AUTO_COMPLETE_FIELDS = {
  title: 'Select IBP CHAPTER',
  item: [
    {
      label: 'NORTHERN LUZON',
      sub_opt: [
        'Abra',
        'Apayao',
        'Baguio-Benguet',
        'Batanes',
        'Cagayan',
        'Ifugao',
        'Ilocos Norte',
        'Ilocos Sur',
        'Isabela',
        'Kalinga',
        'La Union',
        'Mountain Province',
        'Nueva Vizcaya',
        'Quirino',
      ],
    },

    {
      label: 'CENTRAL LUZON',
      sub_opt: [
        'Bataan',
        'Bulacan',
        'Nueva Ecija',
        'Pampanga',
        'Pangasinan',
        'Tarlac',
        'Zambales',
      ],
    },
    {
      label: 'SOUTHERN LUZON',
      sub_opt: [
        'Aurora',
        'Batangas',
        'CAL-MA-NA',
        'Cavite',
        'Laguna',
        'Makati',
        'Marinduque',
        'Occidental Mindoro',
        'Oriental Mindoro',
        'PPLM',
        'Quezon',
        'RSM',
      ],
    },

    {
      label: 'GREATER MANILA',
      sub_opt: [
        'Manila I',
        'Manila II',
        'Manila III',
        'Manila IV',
        'Quezon City',
      ],
    },
    {
      label: 'BICOLANDIA',
      sub_opt: [
        'Albay',
        'Camarines Norte',
        'Camarines Sur',
        'Catanduanes',
        'Masbate',
        'Sorsogon',
      ],
    },
    {
      label: 'EASTERN VISAYAS',
      sub_opt: [
        'Biliran',
        'Bohol',
        'Cebu',
        'Cebu City',
        'Eastern Samar',
        'Leyte',
        'Northern Samar',
        'Samar',
        'Southern Leyte',
      ],
    },
    {
      label: 'WESTERN VISAYAS',
      sub_opt: [
        'Aklan',
        'Antique',
        'Capiz',
        'Guimaras',
        'Iloilo',
        'Negros Occidental',
        'Negros Oriental',
        'Palawan',
        'Romblon',
        'Siquijor',
      ],
    },
    {
      label: 'EASTERN MINDANAO',
      sub_opt: [
        'Agusan Del Norte',
        'Agusan Del Sur',
        'Bukidnon',
        'Camiguin',
        'Davao City',
        'Davao Del Norte',
        'Davao Del Sur',
        'Davao Oriental',
        'Misamis Oriental',
        'Surigao Del Norte',
        'Surigao Del Sur',
      ],
    },
    {
      label: 'WESTERN MINDANAO',
      sub_opt: [
        'Cotabato',
        'Lanao Del Norte',
        'Lanao Del Sur',
        'Misamis Occidental',
        'North Cotabato',
        'South Cotabato',
        'Sarangani',
        'Zambasulta',
        'Zamboanga Del Norte',
        'Zamboanga Del Sur',
        'Zamboanga-Sibugay',
        'Sultan Kudara',
      ],
    },
  ],
};
